### PR TITLE
Added diversity, awesome traits, and added colors to graphs

### LINKED ISSUE #1: Diversity
Right now the model considers all the people have similar interests which is far from true. Add more classes of people for different types of people with different characteristics, different interests(see task-4) like coders, fitness freaks etc. These can inherit functions and attributes from the people class or can be altogether different classes

### LINKED ISSUE #2: Variation of Factors
In the file, change the variation of the factors so that the value remains between 0 and 100. The variation shouldn't just increment or decrement the value by a constant and it should depend on the current level as well. Consider the scenerio for academics for instance, initially you might study a lot but then you reach your saturation point and then the rate would decrease. Don't forget to model this situation! You can use the Gaussian function to model this or even simple if else commands or whatever function you think would be suitable.

### LINKED ISSUE #4: Individual Interests
Each individual has a particular interest or an inclination towards a specific activity. Depending upon the interests, probability to attend a certain event can change drastically. The field of extracurricular activities can also be expanded accordingly. So instead of having the field of extracurricular level you can have fields for different kinds of activities like culturals, sports, tech etc. Also the activity "hobby" will also now change according to your interest. Depending on the interest other factors may get affected as well, like having sports as an hobby will automatically help push your physical fitness.

### PR DESCRIPTION
**Pull request by zestyoreo**
## Description

I have added a coder class and few more functions pertaining to traits of coders (stereotypical ones, though often true ;)<br>
I have changed the simulations.py to accommodate more types of people when I will add them soon.<br>
Also changed the color of each graph to look more attractive.
## Motivation and Context

Diversity and better graphs!
## Review Time Estimate

- [x] Immediately
- [ ] Within one week
- [ ] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have read the CONTRIBUTING.md

### CODE REVIEW

**Comment by Karrthik-Arya** [comment]
The code completes tasks 1 and 4 to add a personality and then add functions and characteristics for that type of personality. For task-2 this solves the issue of the factors exceeding 100 for some of them. However, the rate should also be a function of the current level of that factor instead of a constant increment or decrement. It can be the Gaussian function or the values of the constants can be fixed for different intervals. Also if you want you could send different PRs for different tasks/issues.

**Comment by zestyoreo** [comment]
Will update accordingly.👍

**Comment by zestyoreo** [comment]
Changes have been as suggested. I have used the tanh function to increase/decreate attributes.

**Comment by Karrthik-Arya** [comment]
Most of the code is fine. One small change, the change in the laziness causes an error with randint() since now the upper bound is not an integer so you can use math.floor() to sort this out. Also you can create different branches in the repo and cherry pick the commits to have there and then send separate PRs for each of the tasks. Like this you might be able to get more PRs if you are participating in hacktoberfest.

**Comment by zestyoreo** [comment]
Change done. Next time I commit stuff I will make separate PRs. Thanks for the suggestions.

**Pull request merged**
